version: '3.2'

services:
  php-fpm:
    build: ./docker/php-fpm
    volumes:
      - ./myphp:/var/www
    ports:
      - "9000:9000"

  nginx:
    build: ./docker/nginx
    depends_on:
      - php-fpm
    links:
      - php-fpm:php-fpm
    volumes:
      - ./myphp:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"

  mysql:
    build: ./docker/database
    ports:
        - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: myphp
        MYSQL_USER: root
        MYSQL_PASSWORD: root